# Generated by Django 4.2.3 on 2023-07-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('deposit', models.IntegerField()),
                ('withdrawal', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('account_number', models.IntegerField()),
            ],
        ),
    ]
