# Generated by Django 4.2.3 on 2023-07-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
