# Generated by Django 4.2.3 on 2023-07-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0002_alter_customer_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
    ]
