# Generated by Django 4.2.3 on 2025-05-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0002_alter_customer_balance_alter_customer_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='withdrawal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
