# Generated by Django 4.2.3 on 2025-05-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0003_alter_customer_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
