# Generated by Django 4.2.3 on 2025-05-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_alter_customer_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
