# Generated by Django 4.2.3 on 2025-05-08 12:22

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_customer_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]