# Generated by Django 4.2.3 on 2025-05-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_customer_customer_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='bankapp_customer',
        ),
    ]
