# Generated by Django 4.2.3 on 2025-05-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_alter_customer_table'),
        ('bankapp', '0006_alter_customer_username_alter_user_username'),
    ]

    operations = [
    ]
